version: '2.7'

services:
  backend:
    build: "./api/"
    ports:
      - 8080:8080
  frontend:
    build: "./app/"
    ports:
      - 3000:3000
  database:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      MYSQL_USER: is1ab_admin
      MYSQL_PASSWORD: "is1ab@1321"
      MYSQL_DATABASE: PSS
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: "is1ab#1312"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/:ro