version: '2.7'

services:
  database:
    container_name: pss-database
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "is1ab@1321"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql:ro
  nginx:
    container_name: pss-nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
    depends_on:
      - backend
      - frontend
  backend:
    container_name: pps-backend
    build: "./api/"
    ports:
      - 8080:8080
    depends_on: 
      - database
  frontend:
    container_name: pps-frontend
    build: "./app/"
    ports:
      - 3000:3000
