version: '2.7'

services:
  database:
    container_name: pss-database
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "is1ab_admin"
      POSTGRES_PASSWORD: "is1ab----1321"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql:ro
  nginx:
    container_name: pss-nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
    depends_on:
      - backend
      - frontend
  backend:
    container_name: pps-backend
    build: "./api/"
    depends_on: 
      - database
    environment:
      - PSS_DB_ROLE=is1ab_admin
      - PSS_DB_PASSWORD=is1ab----1321
      - PSS_DB_HOST=pss-database
      - PSS_DB_PORT=5432
  frontend:
    container_name: pps-frontend
    build: "./app/"
